AppType: 0
Vsync: false
ShaderPath: Shader/AutoGen/
ShaderMaterial_FilePath: UnlitShader.hlsli
ShaderMaterial_EntryPoint: ShadeMaterial_Unlit
ShaderMaterial_FilePath: PBRShader.hlsli
ShaderMaterial_EntryPoint: ShadeMaterial_PBR
FullScreen: false
Width: 1280
Height: 720
MasterVolume: 1
BGMVolume: 1
SEVolume: 1