AppType: 0
StartScene: Asset/Game/ElemenTactics/Scene/ElemenTactics.yaml
Vsync: false
MaximumFrameLatency: 3
FullScreen: false
Width: 1280
Height: 720
MasterVolume: 1
BGMVolume: 1
SEVolume: 1
TemplateDir: Asset/Prefab/template
