Systems:
  ScriptSystem: ~
  TransformSystem: ~
  CameraSystem: ~
  RenderSystem:
    ShaderPath: Shader/AutoGen/
    ShaderMaterial:
      UnlitShader.hlsli: ShadeMaterial_Unlit
      PBRShader.hlsli: ShadeMaterial_PBR
      PBRToonShader.hlsli: ShadeMaterial_PBRToon
      ToonShader.hlsli: ShadeMaterial_Toon
      RimToonShader.hlsli: ShadeMaterial_RimToon
      WaterShader.hlsli: ShadeMaterial_Water
      SkyShader.hlsli: ShadeMaterial_Sky
  AudioSystem: ~
  ParticleSystem: ~
  EffectSystem: ~
  TerrainSystem: ~
  PhysicSystem:
    layers:
      - name: Default
        bit: 1
      - name: Player
        bit: 2
      - name: Enemy
        bit: 4
      - name: Environment
        bit: 8
    collision:
      -
        - true
        - true
        - true
        - true
      -
        - true
        - true
        - true
        - true
      -
        - true
        - true
        - true
        - true
      -
        - true
        - true
        - true
        - true
  CustomScriptSystem: ~
  WaveSystem: ~
  FollowSystem: ~