AppType: 0
StartScene: Asset\Scene\scene_title.yaml
Vsync: false
ShaderPath: Shader/AutoGen/
ShaderMaterial:
  UnlitShader.hlsli: ShadeMaterial_Unlit
  PBRShader.hlsli: ShadeMaterial_PBR
FullScreen: false
Width: 1500
Height: 800
MasterVolume: 1
BGMVolume: 1
SEVolume: 1