#pragma once

#include "Backends/ImGui/imgui.h"
#include "Scene/sceneManager.h"
#include "Scene/Registry/systemRegistry.h"
#include "System/Render/RenderSystem/renderSystem.h"
#include "System/Render/RenderSystem/RenderPass/EditorView/EditorPass.h"
#include "System/Render/RenderSystem/RenderPass/GBuffer/GBufferPass.h"
#include "System/Render/RenderSystem/RenderPass/PlayerView/PlayerPass.h"
#include "System/Render/StaticBatch/StaticBatchUploadSystem.h"

namespace StaticBatchTelemetryUI {

inline void DrawSubmissionTelemetry(
	const char* label,
	const GBufferPass* pass
){
	ImGui::SeparatorText(label);
	if(!pass){
		ImGui::TextDisabled("GBufferPass is not available.");
		return;
	}

	const StaticBatchGBufferSubmissionTelemetry& telemetry =
		pass->GetStaticBatchTelemetry();
	if(ImGui::BeginTable(
		label,
		3,
		ImGuiTableFlags_BordersInnerV |
		ImGuiTableFlags_RowBg |
		ImGuiTableFlags_SizingStretchProp
	)){
		ImGui::TableSetupColumn("Metric");
		ImGui::TableSetupColumn("Value");
		ImGui::TableSetupColumn("Meaning");
		ImGui::TableHeadersRow();

		auto row = [](const char* name, std::size_t value, const char* note){
			ImGui::TableNextRow();
			ImGui::TableSetColumnIndex(0);
			ImGui::TextUnformatted(name);
			ImGui::TableSetColumnIndex(1);
			ImGui::Text("%zu", value);
			ImGui::TableSetColumnIndex(2);
			ImGui::TextDisabled("%s", note);
		};

		row("Candidate Groups", telemetry.candidateGroupCount, "Groups generated by the CPU cache");
		row("Visible Instances", telemetry.visibleInstanceCount, "Instances selected for this Player or Editor view");
		row("Culled Instances", telemetry.culledInstanceCount, "Instances omitted from the view-local GPU upload");
		row("Compacted Mixed Groups", telemetry.compactedMixedGroupCount, "Partially visible source groups rebuilt as visible-only groups");
		row("Submitted Groups", telemetry.submittedGroupCount, "Groups replaced by DrawIndexedInstanced");
		row("Submitted Instances", telemetry.submittedInstanceCount, "Instances emitted through the static path");
		row(
			"Ordinary Draws Replaced",
			telemetry.ReplacedOrdinaryDrawCallCount(),
			"Single-submesh ordinary draws removed from this GBuffer pass"
		);
		row(
			"Static Draw Calls",
			telemetry.StaticDrawCallCount(),
			"DrawIndexedInstanced calls issued by the static path"
		);
		row(
			"Estimated Draw Reduction",
			telemetry.EstimatedDrawCallReduction(),
			"Ordinary draws replaced minus static draw calls"
		);
		row("Selection Failures", telemetry.visibilitySelectionFailureCount, "View-local compaction failed and ordinary packets were preserved");
		row("Single Instance", telemetry.singleInstanceFallbackCount, "Visible-only groups too small to instance");
		row("Invalid Packet Range", telemetry.packetRangeFallbackCount, "Packet index or uint32 range validation failed");
		row("Layer Fallback", telemetry.layerFallbackCount, "Layer was hidden or invalid");
		row("Culled Groups", telemetry.culledGroupCount, "All instances were outside the current view");
		row("Legacy Mixed Fallback", telemetry.mixedVisibilityFallbackCount, "Mixed groups that could not use compaction");
		row("Geometry Fallback", telemetry.geometryFallbackCount, "Geometry import/cache was unavailable");
		row("Material Fallback", telemetry.materialFallbackCount, "Material or texture equivalence was not proven");
		row("Draw Failures", telemetry.drawFailureCount, "Command creation, upload, or DrawIndexedInstanced failed");
		row("Queue Failures", telemetry.queueFailureCount, "Graphics Queue submission failed");
		row("Target Failures", telemetry.targetBindingFailureCount, "GBuffer RTV/DSV validation failed");
		ImGui::EndTable();
	}

	ImGui::Text(
		"Pipeline: %s | View Upload: %s | Revision: %llu",
		telemetry.pipelineReady ? "Ready" : "Unavailable",
		telemetry.instanceUploadReady ? "Ready" : "Unavailable",
		static_cast<unsigned long long>(telemetry.sourceRevision)
	);
}

inline void Draw(SceneManager* sceneManager){
	SystemRegistry* registry =
		sceneManager ? sceneManager->GetSystemRegistry() : nullptr;
	if(!registry){
		ImGui::TextDisabled("SystemRegistry is not available.");
		return;
	}

	StaticBatchUploadSystem* upload =
		registry->GetSystem<StaticBatchUploadSystem>();
	RenderSystem* render = registry->GetSystem<RenderSystem>();

	ImGui::SeparatorText("Source Upload / Geometry Cache");
	if(!upload){
		ImGui::TextDisabled("StaticBatchUploadSystem is not available.");
	}else{
		const StaticBatchGpuInstanceBufferTelemetry instance =
			upload->GetTelemetry();
		const StaticBatchGeometryBindingCacheTelemetry geometry =
			upload->GetGeometryTelemetry();

		ImGui::Text(
			"Pipeline: %s | Source Upload: %s",
			upload->IsPipelineReady() ? "Ready" : "Unavailable",
			upload->LastUploadSucceeded() ? "Succeeded" : "Unavailable"
		);
		ImGui::Text(
			"Source Instances: %zu / %zu | Uploads: %zu | Reallocations: %zu | Failures: %zu",
			instance.currentInstanceCount,
			instance.instanceCapacity,
			instance.uploadCount,
			instance.reallocationCount,
			instance.failedUploadCount
		);
		ImGui::Text(
			"Geometry Bindings: %zu | Resolved Groups: %zu | Creates: %zu | Reuses: %zu",
			geometry.currentBindingCount,
			geometry.currentResolvedGroupCount,
			geometry.createCount,
			geometry.reuseCount
		);
		ImGui::Text(
			"Geometry Rejects: %zu | Import Failures: %zu | Conflicts: %zu | Release Failures: %zu",
			geometry.rejectedGroupCount,
			geometry.importFailureCount,
			geometry.sourceConflictCount,
			geometry.releaseFailureCount
		);
	}

	const GBufferPass* playerPass =
		render && render->m_PlayerPass
			? render->m_PlayerPass->gBufferPass
			: nullptr;
	const GBufferPass* editorPass =
		render && render->m_EditorPass
			? render->m_EditorPass->gBufferPass
			: nullptr;
	DrawSubmissionTelemetry("Player GBuffer", playerPass);
	DrawSubmissionTelemetry("Editor GBuffer", editorPass);
}

} // namespace StaticBatchTelemetryUI
