# Native package build. The target is explicit, and a wrong host fails before
# configuring rather than silently creating a package for a different OS.
cmake_minimum_required(VERSION 3.24)
if(NOT DEFINED SOURCE_DIR)
  get_filename_component(SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()
if(NOT DEFINED TARGET_PLATFORM)
  message(FATAL_ERROR "Specify -DTARGET_PLATFORM=Windows or macOS")
endif()
if(NOT TARGET_PLATFORM STREQUAL CMAKE_HOST_SYSTEM_NAME)
  # CMake calls macOS Darwin internally.
  if(NOT (TARGET_PLATFORM STREQUAL "macOS" AND CMAKE_HOST_SYSTEM_NAME STREQUAL "Darwin"))
    message(FATAL_ERROR "${TARGET_PLATFORM} packages require that OS or its CI runner. Current host: ${CMAKE_HOST_SYSTEM_NAME}")
  endif()
endif()
if(NOT DEFINED CONFIGURATION)
  set(CONFIGURATION Release)
endif()
if(NOT CONFIGURATION MATCHES "^(Debug|Release)$")
  message(FATAL_ERROR "CONFIGURATION must be Debug or Release")
endif()
set(build "${SOURCE_DIR}/build-portable-${TARGET_PLATFORM}")
set(package "${SOURCE_DIR}/portable-runtime/${TARGET_PLATFORM}/${CONFIGURATION}")
set(configure_args -S "${SOURCE_DIR}" -B "${build}" "-DCMAKE_BUILD_TYPE=${CONFIGURATION}")
if(DEFINED SDL3_DIR)
  list(APPEND configure_args "-DSDL3_DIR=${SDL3_DIR}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" ${configure_args} COMMAND_ERROR_IS_FATAL ANY)
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${build}" --config "${CONFIGURATION}" --parallel 4 COMMAND_ERROR_IS_FATAL ANY)
execute_process(COMMAND "${CMAKE_COMMAND}" --install "${build}" --config "${CONFIGURATION}" --prefix "${package}" COMMAND_ERROR_IS_FATAL ANY)
message(STATUS "Package: ${package}")
