# One GLSL source set -> SPIR-V, DXIL and MSL. No runtime compiler is required.
foreach(tool GLSLC SPIRV_CROSS DXC)
  if(NOT EXISTS "${${tool}}")
    message(FATAL_ERROR "${tool} must name an installed shader compiler")
  endif()
endforeach()
function(run)
  execute_process(COMMAND ${ARGV} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Shader command failed (${result}): ${ARGV}\n${output}\n${error}")
  endif()
endfunction()
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
foreach(shader geometry.vert geometry.frag shadow.vert shadow.frag fullscreen.vert lighting.frag tonemap.frag present.frag fill.comp)
  if(shader MATCHES "\\.vert$")
    set(profile vs_6_0)
  elseif(shader MATCHES "\\.comp$")
    set(profile cs_6_0)
  else()
    set(profile ps_6_0)
  endif()
  run("${GLSLC}" --target-env=vulkan1.0 "${SOURCE_DIR}/${shader}" -o "${OUTPUT_DIR}/${shader}.spv")
  run("${SPIRV_CROSS}" "${OUTPUT_DIR}/${shader}.spv" --hlsl --shader-model 60 --output "${OUTPUT_DIR}/${shader}.hlsl")
  run("${DXC}" -T ${profile} -E main -Fo "${OUTPUT_DIR}/${shader}.dxil" "${OUTPUT_DIR}/${shader}.hlsl")
  run("${SPIRV_CROSS}" "${OUTPUT_DIR}/${shader}.spv" --msl --msl-version 20100 --msl-decoration-binding --output "${OUTPUT_DIR}/${shader}.msl")
  foreach(extension hlsl msl)
    file(READ "${OUTPUT_DIR}/${shader}.${extension}" generated)
    string(REGEX REPLACE "[ \t\r\n]+$" "" generated "${generated}")
    file(WRITE "${OUTPUT_DIR}/${shader}.${extension}" "${generated}\n")
  endforeach()
endforeach()
